name: "@thnetii/gh-actions-prettier"
author: thnetii
description: ""
inputs:
  arguments:
    required: false
    description: ""
    default: "."
  working-directory:
    default: ${{ github.workspace }}
    description: ""
    required: false
  github-workspace:
    default: ${{ github.workspace }}
    description: ""
    required: false
  npm-exec-packages:
    description: ""
    required: false
  npm-exec-allow-package-install:
    description: ""
    required: false
  npm-workspace:
    description: ""
    required: false
  npm-workspaces:
    description: ""
    default: "false"
    required: false
  npm-include-workspace-root:
    description: ""
    default: "false"
    required: false
outputs:
  prettier-exitcode:
    description: ""
runs:
  using: node20
  pre: setup.js
  main: action.js
