version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 50
    schedule:
      interval: daily
    reviewers:
      - thnetii/organization
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 50
    schedule:
      interval: daily
    reviewers:
      - thnetii/organization
