root: true
env:
  es2023: true
  node: true
parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  babelOptions:
    babelrc: false
    configFile: false
    presets: ["@babel/preset-env"]
extends:
  - ../../.eslintrc.yml
rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
        - dynamicImport
  node/no-missing-import: off
  import/extensions: off
