name: "@thnetii/gh-actions-get-workflow-id"
author: thnetii
description: ""
runs:
  using: composite
  steps:
    - id: get-workflow-id
      uses: actions/github-script@v7.0.1
      with:
        script: |
          require(process.env['GITHUB_ACTION_PATH'])(
            { github, context, core }
          );
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
outputs:
  workflow-id:
    description: The unique Id of the GitHub Actions workflow that is currently running.
    value: ${{ steps.get-workflow-id.outputs.workflow-id }}
