name: "@thnetii/gh-actions-create-rebase-pr-branch"
author: thnetii
description: ""
inputs:
  branch-name:
    required: true
    description: ""
  repository:
    required: false
    default: ${{ github.repository }}
    description: ""
  working-directory:
    required: false
    default: ${{ github.workspace }}
    description: ""

runs:
  using: composite
  steps:
    - id: create-rebase-pr-branch
      uses: actions/github-script@v7.0.1
      with:
        script: |
          require(process.env['GITHUB_ACTION_PATH'])(
            {
              github, context, core, exec,
              inputs: JSON.parse(process.env['ACTION_INPUTS_JSON']),
            }
          );
      env:
        ACTION_INPUTS_JSON: ${{ toJson(inputs) }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
outputs: {}
