name: "@thnetii/gh-actions-exec"
author: thnetii
description: ""
inputs:
  command:
    required: true
    description: ""
  arguments:
    description: ""
  working-directory:
    default: ${{ github.workspace }}
    description: ""
    required: false
outputs:
  command-exitcode:
    description: ""
    value: ${{ steps.exec-command.outputs.command-exitcode }}
runs:
  using: composite
  steps:
    - id: exec-command
      uses: actions/github-script@v7.0.1
      with:
        script: |
          require(process.env['GITHUB_ACTION_PATH'])(
            { core, exec }
          );
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
