name: "@thnetii/gh-actions-npm"
author: thnetii
description: ""
inputs:
  arguments:
    required: true
    description: ""
  working-directory:
    default: ${{ github.workspace }}
    description: ""
    required: false
runs:
  using: node20
  pre: setup.js
  main: action.js
