name: Code Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  root:
    name: Node.js
    uses: ./.github/workflows/nodejs-lint-reusable.yml
    with:
      npm-install-check-enable: true
      tsc-check-enable: true
      tsc-parameters: >
        {
          "arguments": "--noEmit\n-p\n./jsconfig.json"
        }
      eslint-check-enable: true
      prettier-check-enable: true
